### ISSUE TITLE
Build requests from Annotator may not execute due to build systems caching strategy.

### ISSUE THREAD

**Issue by nimakarimipour** [nimakarimipour/NullAwayAnnotator#38]
**Describe the bug**
In environments where the build system is extensively using caching strategies, a build request from Annotator may not execute if no file is modified under the module directory. Even if config files of annotator are written inside the module, since config files content can be identical within build request, it might hit the cache and the using build system will not rebuild the module. If the project is not rebuilt, annotator will not correctly compute the effectiveness of fixes and the serialization outputs may not be even located.

**To Reproduce**
Re-use the AutoAnnotator

**Expected behavior**
When ever annotator is requesting a build, all `Error Prone` checkers should re-execute.

**Screenshots**
Not-Applicable.

**OS (please complete the following information):**
 - OS: Linux
 - Annotator Version: v1.3.2-SNAPSHOT

**Additional context**
Not-Applicable.

**Comment by lazaroclapp** [comment]
Just to be clear, the way our scanner and NullAway output work are that as long as they get passed:

1. The same source code
2. The same config XML

Then the resulting TSV files _should_ always be the same. Correct? (i.e. it's not reading any cross-build state from our annotator temporary directories).

If so, then a solution is to make sure those TSV files are output to whatever the output directory of the build system is (e.g. `$OUT` for the target in buck), which will cause the build cache to also cache those files, so they will be there when the target is rebuilt.

This needs some tighter integration with the build system and yet another path being passed per-target by some coordinator script, so I think we are better off with the UUID approach for now, but it's worth keeping in mind that we could do this by leveraging the cache, rather than invalidating it, and it might make the tool faster. How much faster depends on how often the annotator requests the exact same (source, config) pair to be built 🙂

**Comment by nimakarimipour** [comment]
Yes sure, that makes sense. Also the other concern that I have is that, let's assume that annotator is working on `n` modules to analyze downstream dependencies and for any reason the user stop the process or it end with an exception that does not let the tool to clear all the generated files (including config files). Now the only way to properly restart the process is to manually delete those files on `n` modules which I think the approach you mentioned should also cover that (not sure yet). I wasn't aware that we can also cache custom generated outputs and it is really interesting. We can definitely work on that and improve it 🙂.
